In [3]:
import numpy as np
import pandas as pd
from datetime import datetime

import vectorbt as vbt

# Prepare data
start = '2019-01-01 UTC'  # crypto is in UTC
end = '2020-01-01 UTC'
btc_price = vbt.YFData.download('BTC-USD', start=start, end=end).get('Close')

btc_price

Date
2019-01-01 00:00:00+00:00    3843.520020
2019-01-02 00:00:00+00:00    3943.409424
2019-01-03 00:00:00+00:00    3836.741211
2019-01-04 00:00:00+00:00    3857.717529
2019-01-05 00:00:00+00:00    3845.194580
                                ...
2019-12-27 00:00:00+00:00    7290.088379
2019-12-28 00:00:00+00:00    7317.990234
2019-12-29 00:00:00+00:00    7422.652832
2019-12-30 00:00:00+00:00    7292.995117
2019-12-31 00:00:00+00:00    7193.599121
Freq: D, Name: Close, Length: 365, dtype: float64

In [4]:
fast_ma = vbt.MA.run(btc_price, 10, short_name='fast')
slow_ma = vbt.MA.run(btc_price, 20, short_name='slow')

entries = fast_ma.ma_crossed_above(slow_ma)
entries

Date
2019-01-01 00:00:00+00:00    False
2019-01-02 00:00:00+00:00    False
2019-01-03 00:00:00+00:00    False
2019-01-04 00:00:00+00:00    False
2019-01-05 00:00:00+00:00    False
                             ...
2019-12-27 00:00:00+00:00     True
2019-12-28 00:00:00+00:00    False
2019-12-29 00:00:00+00:00    False
2019-12-30 00:00:00+00:00    False
2019-12-31 00:00:00+00:00    False
Freq: D, Length: 365, dtype: bool

In [5]:
exits = fast_ma.ma_crossed_below(slow_ma)
exits

Date
2019-01-01 00:00:00+00:00    False
2019-01-02 00:00:00+00:00    False
2019-01-03 00:00:00+00:00    False
2019-01-04 00:00:00+00:00    False
2019-01-05 00:00:00+00:00    False
                             ...
2019-12-27 00:00:00+00:00    False
2019-12-28 00:00:00+00:00    False
2019-12-29 00:00:00+00:00    False
2019-12-30 00:00:00+00:00    False
2019-12-31 00:00:00+00:00    False
Freq: D, Length: 365, dtype: bool

In [6]:
pf = vbt.Portfolio.from_signals(btc_price, entries, exits)
pf.total_return()

np.float64(0.6351860771192923)

In [7]:
# Multiple strategy instances: (10, 30) and (20, 30)
fast_ma = vbt.MA.run(btc_price, [10, 20], short_name='fast')
slow_ma = vbt.MA.run(btc_price, [30, 30], short_name='slow')

entries = fast_ma.ma_crossed_above(slow_ma)
entries

fast_window                   10     20
slow_window                   30     30
Date
2019-01-01 00:00:00+00:00  False  False
2019-01-02 00:00:00+00:00  False  False
2019-01-03 00:00:00+00:00  False  False
2019-01-04 00:00:00+00:00  False  False
2019-01-05 00:00:00+00:00  False  False
...                          ...    ...
2019-12-27 00:00:00+00:00  False  False
2019-12-28 00:00:00+00:00  False  False
2019-12-29 00:00:00+00:00   True  False
2019-12-30 00:00:00+00:00  False  False
2019-12-31 00:00:00+00:00  False  False

[365 rows x 2 columns]

In [8]:
exits = fast_ma.ma_crossed_below(slow_ma)
exits

fast_window                   10     20
slow_window                   30     30
Date
2019-01-01 00:00:00+00:00  False  False
2019-01-02 00:00:00+00:00  False  False
2019-01-03 00:00:00+00:00  False  False
2019-01-04 00:00:00+00:00  False  False
2019-01-05 00:00:00+00:00  False  False
...                          ...    ...
2019-12-27 00:00:00+00:00  False  False
2019-12-28 00:00:00+00:00  False  False
2019-12-29 00:00:00+00:00  False  False
2019-12-30 00:00:00+00:00  False  False
2019-12-31 00:00:00+00:00  False  False

[365 rows x 2 columns]

In [9]:
pf = vbt.Portfolio.from_signals(btc_price, entries, exits)
pf.total_return()

fast_window  slow_window
10           30             0.847151
20           30             0.543411
Name: total_return, dtype: float64